# Site settings
title: > 
  49-3 : On s'en souviendra
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  49-3 : On s'en souviendra ! 
  Lettres ouvertes aux députés, et archivage de leurs votes pour les motions de censure au 49-3.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://onsensouviendra.fr" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

page_gen:
  - data: 'deputes'
    template: 'depute'
    name: 'id'
    dir: 'deputes'

# Build settings
markdown: kramdown
